### PR TITLE
human readable info presentation

### PR DESCRIPTION
**Pull request by borism**

### CODE REVIEW

**Review by sivang — COMMENTED** [review]
So, I tested that locally and the page looks like this:
image

The table seems a bit broken , is this intended?

**Comment by borism** [comment]
@sivang not intentional, fixed

**Review by sivang — CHANGES_REQUESTED** [review]
Cool, this is much better - a few corrections though:
image
- We need a space between `machine_architecture` and the reported value.
- Let's split the strings by the `_` and titlize them to make them really human readable.
- If a field has no value, let's put there 'N/A' instead of blank.
- Let's break the list of extensions and humanize their display so it's not just a printout of the list.
- Let's change the colors to match CKAN's basic out of the box theming.
- Also expand the space between `error_emails_to` and ` None` (and make sure this becomes N/A as per previous.)
- Truncate `load_average_5min` to have 2 digits after the decimal point.

**Comment by borism** [comment]
let's not make this too nice - we know that end users for this are developers and sysadmins who can read `None` and `_`.

I made some changes that improve readability though.

**Pull request merged**
